-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

  Slave node 292 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 501 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 108 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 271 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 259 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 488 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 258 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 500 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 109 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 298 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 110 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 2 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 319 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 504 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 103 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 275 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 574 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 232 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 307 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 503 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 105 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 324 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 104 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 313 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 99 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 308 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 100 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 305 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 310 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 523 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 20 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 287 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 21 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 7 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 199 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 499 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 102 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 498 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 111 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 142 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 112 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 49 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 36 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 519 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 36 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 498 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 4 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 109 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 4 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 43 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 195 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 518 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 9 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 226 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 8 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 48 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 101 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 519 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 193 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 518 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 82 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 151 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 81 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 109 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 200 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 499 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 25 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 214 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 26 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 121 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 1 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 69 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 1 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 52 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 83 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 223 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 296 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 489 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 106 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 301 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 107 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 215 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 309 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 514 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 89 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 304 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 88 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 229 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 290 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 516 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 299 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 515 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 86 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 201 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 86 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 145 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 87 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 145 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 85 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 295 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 326 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 521 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 95 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 306 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 308 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 521 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 314 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 509 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 15 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 251 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 16 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 163 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 303 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 520 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 19 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 259 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 18 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 173 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 17 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 260 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 13 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 310 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 14 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 286 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 12 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 302 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 23 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 300 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 24 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 263 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 262 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 517 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 84 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 296 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 261 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 516 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 11 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 291 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 10 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 226 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 328 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 130 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 101 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 305 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 102 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 294 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 313 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 497 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 315 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 505 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 577 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 305 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 575 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 305 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 570 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 287 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 576 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 287 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 94 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 326 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 93 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 317 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 317 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 511 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 325 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 510 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 573 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 316 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 571 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 303 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 322 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 496 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 91 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 323 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 92 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 303 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 569 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 303 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 333 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 491 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 96 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 327 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 97 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 318 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 22 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 320 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 321 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 508 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 578 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 322 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 98 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 321 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 320 of instance PLAQUE-1 is nearly coincident with the reference
  plane of the double-sided element 513 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 572 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 316 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 90 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 304 of instance PLAQUE-1 in the
  configuration before the initial overclosure procedure.


  Slave node 267 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 565 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 141 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 207 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 208 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 565 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 191 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 118 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 190 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 3 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 189 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 193 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 140 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 193 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 135 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 230 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 136 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 222 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 357 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 542 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 137 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 224 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 274 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 545 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 133 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 333 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 130 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 281 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 129 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 334 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 128 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 241 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 207 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 566 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 212 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 557 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 158 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 213 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 159 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 208 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 214 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 542 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 216 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 541 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 186 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 220 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 138 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 219 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 356 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 553 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 241 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 552 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 166 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 185 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 165 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 10 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 240 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 553 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 164 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 228 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 245 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 547 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 236 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 547 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 174 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 242 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 175 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 190 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 252 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 560 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 251 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 548 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 173 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 255 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 127 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 273 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 194 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 258 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 34 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 559 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 34 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 537 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 7 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 112 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 7 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 66 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 182 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 149 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 177 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 194 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 243 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 551 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 123 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 246 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 242 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 535 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 167 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 34 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 246 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 550 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 244 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 550 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 360 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 550 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 168 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 158 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 169 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 91 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 97 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 559 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 155 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 203 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 156 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 114 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 194 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 569 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 98 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 537 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 144 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 47 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 5 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 110 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 5 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 67 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 198 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 558 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 113 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 44 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 193 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 182 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 204 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 566 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 115 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 268 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 157 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 177 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 114 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 46 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 239 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 567 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 234 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 554 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 163 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 225 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 223 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 534 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 162 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 274 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 215 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 541 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 187 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 73 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 213 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 540 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 139 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 270 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 188 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 193 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 222 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 530 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 220 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 543 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 184 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 167 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 183 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 140 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 219 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 564 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 217 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 564 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 185 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 168 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 225 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 544 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 180 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 277 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 181 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 166 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 230 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 562 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 231 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 562 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 132 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 235 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 179 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 137 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 178 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 125 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 235 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 561 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 233 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 546 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 176 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 152 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 250 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 560 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 172 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 250 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 247 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 568 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 248 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 549 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 125 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 249 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 171 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 248 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 170 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 247 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 124 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 337 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 121 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 312 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 122 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 284 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 205 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 538 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 206 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 538 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 192 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 202 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 143 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 146 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 142 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 141 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 116 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 153 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 218 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 556 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 221 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 555 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 117 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 269 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 160 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 184 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 232 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 546 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 131 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 239 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 249 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 532 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 126 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 314 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 120 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 240 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 119 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 234 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 351 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 555 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 354 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 554 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 271 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 554 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 118 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 299 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 161 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 200 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Slave node 224 of instance PLAQUE-2 is nearly coincident with the reference
  plane of the double-sided element 563 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Slave node 134 of instance POT2-1 is nearly coincident with the reference
  plane of the double-sided element 231 of instance PLAQUE-2 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 292 and 300 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 125 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 292 and 294 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 124 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 259 and 294 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 123 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 259 and 263 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 122 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 258 and 284 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 4 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 319 and 350 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 129 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 319 and 345 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 6 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 307 and 350 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 129 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 307 and 323 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 128 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 307 and 312 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 127 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 307 and 345 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 6 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 307 and 346 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 5 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 310 and 345 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 7 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 199 and 263 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 122 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 199 and 265 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 122 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 102 and 196 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 121 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 102 and 104 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 1 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 196 and 199 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 121 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 100 and 102 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 120 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 36 and 99 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 152 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 36 and 100 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 120 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 36 and 37 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 20 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 36 and 37 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 1 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 36 and 37 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 1 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 35 and 36 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 152 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 35 and 36 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 152 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 35 and 36 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 120 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 35 and 36 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 120 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 192 and 193 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 150 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 99 and 101 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 151 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 195 and 201 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 19 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 195 and 260 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 149 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 103 and 193 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 19 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 103 and 195 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 19 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 193 and 264 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 150 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 193 and 260 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 150 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 101 and 192 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 151 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 101 and 103 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 20 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 202 and 258 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 3 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 203 and 258 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 3 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 203 and 259 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 3 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 200 and 203 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 2 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 200 and 263 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 122 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 106 and 200 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 2 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 104 and 200 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 2 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 104 and 199 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 1 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 37 and 101 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 20 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 37 and 102 of instance PLAQUE-1 may be on the same side
  of a surface near face SPOS of element 1 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 281 and 325 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 140 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 201 and 262 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 18 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 201 and 261 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 17 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 197 and 261 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 17 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 105 and 195 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 19 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 260 and 262 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 149 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 305 and 307 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 127 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 296 and 305 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 126 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 296 and 300 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 125 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 296 and 346 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 5 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 309 and 316 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 145 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 309 and 327 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 144 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 299 and 304 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 146 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 299 and 316 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 145 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 290 and 304 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 147 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 290 and 291 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 147 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 326 and 331 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 137 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 326 and 342 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 137 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 326 and 339 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 137 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 326 and 341 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 137 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 314 and 331 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 138 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 308 and 318 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 11 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 302 and 317 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 13 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 302 and 314 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 12 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 302 and 308 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 11 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 289 and 308 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 11 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 303 and 318 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 10 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 303 and 330 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 134 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 288 and 303 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 9 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 301 and 313 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 8 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 301 and 303 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 9 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 301 and 310 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 7 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 286 and 310 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 7 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 318 and 333 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 10 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 318 and 321 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 10 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 298 and 303 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 9 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 306 and 309 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 15 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 306 and 317 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 14 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 306 and 320 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 14 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 297 and 299 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 16 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 297 and 309 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 15 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 284 and 296 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 4 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 262 and 347 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 149 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 262 and 291 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 148 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 285 and 290 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 17 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 285 and 299 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 16 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 261 and 285 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 17 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 261 and 291 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 148 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 328 and 350 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 129 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 315 and 324 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 132 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 315 and 332 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 131 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 313 and 324 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 133 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 313 and 330 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 134 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 283 and 325 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 139 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 325 and 329 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 140 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 325 and 331 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 138 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 322 and 334 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 142 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 322 and 329 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 141 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 322 and 338 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 141 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 333 and 342 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 136 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 333 and 337 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 136 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 321 and 337 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 135 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 321 and 330 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 134 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 320 and 327 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 143 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 320 and 334 of instance PLAQUE-1 may be on the same
  side of a surface near face SPOS of element 142 of instance POT2-1 but still
  crossed the surface in the configuration before the initial overclosure
  procedure.


  Adjacent slave nodes 269 and 348 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 157 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 267 and 269 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 157 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 267 and 349 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 156 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 267 and 294 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 156 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 208 and 349 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 156 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 211 and 269 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 157 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 353 and 357 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 160 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 312 and 357 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 160 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 274 and 280 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 165 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 274 and 332 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 165 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 274 and 340 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 165 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 212 and 293 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 182 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 212 and 266 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 181 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 209 and 293 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 182 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 207 and 293 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 182 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 207 and 264 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 183 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 216 and 270 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 160 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 216 and 311 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 159 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 214 and 270 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 160 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 270 and 357 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 160 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 241 and 343 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 176 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 241 and 361 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 175 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 238 and 343 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 176 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 240 and 355 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 178 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 240 and 278 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 177 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 245 and 339 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 170 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 245 and 342 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 169 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 236 and 342 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 169 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 236 and 352 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 168 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 252 and 341 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 171 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 251 and 339 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 170 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 251 and 341 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 170 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 34 and 35 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 185 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 34 and 35 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 153 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 34 and 35 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 153 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 279 and 360 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 174 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 243 and 279 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 175 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 242 and 279 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 175 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 242 and 361 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 175 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 246 and 276 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 174 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 246 and 359 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 173 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 97 and 99 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 185 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 196 and 205 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 155 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 194 and 196 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 154 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 100 and 194 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 154 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 98 and 100 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 153 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 35 and 97 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 185 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 35 and 98 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 153 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 192 and 198 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 184 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 192 and 204 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 183 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 99 and 198 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 184 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 204 and 264 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 183 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 239 and 355 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 178 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 239 and 273 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 179 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 234 and 273 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 179 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 215 and 311 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 159 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 215 and 268 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 159 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 213 and 269 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 158 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 213 and 268 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 158 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 222 and 272 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 162 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 220 and 358 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 162 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 220 and 272 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 162 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 219 and 358 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 161 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 219 and 353 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 161 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 225 and 340 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 164 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 225 and 275 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 163 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 231 and 280 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 166 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 231 and 336 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 166 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 230 and 280 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 166 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 235 and 277 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 168 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 235 and 352 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 168 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 233 and 277 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 168 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 250 and 341 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 171 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 248 and 359 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 173 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 248 and 281 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 172 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 247 and 359 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 173 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 276 and 360 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 174 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 343 and 356 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 176 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 206 and 349 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 156 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 206 and 265 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 155 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 205 and 265 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 155 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 218 and 266 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 181 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 218 and 295 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 181 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 232 and 336 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 167 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 232 and 277 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 167 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 232 and 282 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 167 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 249 and 283 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 172 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 249 and 281 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 172 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 249 and 341 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 171 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 295 and 351 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 180 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 327 and 356 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 177 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 278 and 356 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 177 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 304 and 354 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 179 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 304 and 351 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 180 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 273 and 354 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 179 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 271 and 304 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 179 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 224 and 275 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 163 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 224 and 272 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 162 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Adjacent slave nodes 338 and 360 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 174 of instance POT2-1 in the
  configuration before the initial overclosure procedure.


  Abaqus/Explicit will attempt to resolve 230 initial node-face overclosure(s).


Initial node-face overclosure is 7.50000E-02 at node 108 of instance POT2-1 and face SNEG of element 271 of instance PLAQUE-1
Initial node-face overclosure is 8.78322E-02 at node 292 of instance PLAQUE-1 and face SNEG of element 501 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 109 of instance POT2-1 and face SNEG of element 298 of instance PLAQUE-1
Initial node-face overclosure is 9.82033E-02 at node 259 of instance PLAQUE-1 and face SNEG of element 488 of instance POT2-1
Initial node-face overclosure is 0.12048 at node 258 of instance PLAQUE-1 and face SNEG of element 500 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 110 of instance POT2-1 and face SNEG of element 2 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 574 of instance POT2-1 and face SNEG of element 232 of instance PLAQUE-1
Initial node-face overclosure is 7.49981E-02 at node 103 of instance POT2-1 and face SNEG of element 275 of instance PLAQUE-1
Initial node-face overclosure is 5.46282E-02 at node 350 of instance PLAQUE-1 and face SNEG of element 129 of instance POT2-1
Initial node-face overclosure is 0.10524 at node 319 of instance PLAQUE-1 and face SNEG of element 504 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 105 of instance POT2-1 and face SNEG of element 324 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 104 of instance POT2-1 and face SNEG of element 313 of instance PLAQUE-1
Initial node-face overclosure is 9.73998E-02 at node 307 of instance PLAQUE-1 and face SNEG of element 503 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 100 of instance POT2-1 and face SNEG of element 305 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 99 of instance POT2-1 and face SNEG of element 308 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 21 of instance POT2-1 and face SNEG of element 7 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 20 of instance POT2-1 and face SNEG of element 287 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 310 of instance PLAQUE-1 and face SNEG of element 523 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 112 of instance POT2-1 and face SNEG of element 49 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 111 of instance POT2-1 and face SNEG of element 142 of instance PLAQUE-1
Initial node-face overclosure is 8.56718E-02 at node 199 of instance PLAQUE-1 and face SNEG of element 499 of instance POT2-1
Initial node-face overclosure is 9.18131E-02 at node 102 of instance PLAQUE-1 and face SNEG of element 498 of instance POT2-1
Initial node-face overclosure is 7.49990E-02 at node 4 of instance POT2-1 and face SNEG of element 109 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 4 of instance POT2-1 and face SNEG of element 43 of instance PLAQUE-1
Initial node-face overclosure is 9.16667E-02 at node 36 of instance PLAQUE-1 and face SNEG of element 519 of instance POT2-1
Initial node-face overclosure is 9.16667E-02 at node 36 of instance PLAQUE-1 and face SNEG of element 498 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 9 of instance POT2-1 and face SNEG of element 226 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 8 of instance POT2-1 and face SNEG of element 48 of instance PLAQUE-1
Initial node-face overclosure is 0.11746 at node 195 of instance PLAQUE-1 and face SNEG of element 518 of instance POT2-1
Initial node-face overclosure is 7.49971E-02 at node 82 of instance POT2-1 and face SNEG of element 151 of instance PLAQUE-1
Initial node-face overclosure is 7.49981E-02 at node 81 of instance POT2-1 and face SNEG of element 109 of instance PLAQUE-1
Initial node-face overclosure is 8.24448E-02 at node 193 of instance PLAQUE-1 and face SNEG of element 518 of instance POT2-1
Initial node-face overclosure is 9.12450E-02 at node 101 of instance PLAQUE-1 and face SNEG of element 519 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 26 of instance POT2-1 and face SNEG of element 121 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 25 of instance POT2-1 and face SNEG of element 214 of instance PLAQUE-1
Initial node-face overclosure is 0.11747 at node 200 of instance PLAQUE-1 and face SNEG of element 499 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 1 of instance POT2-1 and face SNEG of element 69 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 1 of instance POT2-1 and face SNEG of element 52 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 83 of instance POT2-1 and face SNEG of element 223 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 107 of instance POT2-1 and face SNEG of element 215 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 106 of instance POT2-1 and face SNEG of element 301 of instance PLAQUE-1
Initial node-face overclosure is 0.10014 at node 296 of instance PLAQUE-1 and face SNEG of element 489 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 89 of instance POT2-1 and face SNEG of element 304 of instance PLAQUE-1
Initial node-face overclosure is 7.49981E-02 at node 88 of instance POT2-1 and face SNEG of element 229 of instance PLAQUE-1
Initial node-face overclosure is 0.10288 at node 309 of instance PLAQUE-1 and face SNEG of element 514 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 87 of instance POT2-1 and face SNEG of element 145 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 86 of instance POT2-1 and face SNEG of element 145 of instance PLAQUE-1
Initial node-face overclosure is 9.93465E-02 at node 299 of instance PLAQUE-1 and face SNEG of element 515 of instance POT2-1
Initial node-face overclosure is 8.65889E-02 at node 290 of instance PLAQUE-1 and face SNEG of element 516 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 85 of instance POT2-1 and face SNEG of element 295 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 95 of instance POT2-1 and face SNEG of element 306 of instance PLAQUE-1
Initial node-face overclosure is 7.82696E-02 at node 326 of instance PLAQUE-1 and face SNEG of element 521 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 16 of instance POT2-1 and face SNEG of element 163 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 15 of instance POT2-1 and face SNEG of element 251 of instance PLAQUE-1
Initial node-face overclosure is 0.10691 at node 314 of instance PLAQUE-1 and face SNEG of element 509 of instance POT2-1
Initial node-face overclosure is 0.12202 at node 308 of instance PLAQUE-1 and face SNEG of element 521 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 19 of instance POT2-1 and face SNEG of element 259 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 18 of instance POT2-1 and face SNEG of element 173 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 303 of instance PLAQUE-1 and face SNEG of element 520 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 17 of instance POT2-1 and face SNEG of element 260 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 14 of instance POT2-1 and face SNEG of element 286 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 13 of instance POT2-1 and face SNEG of element 310 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 12 of instance POT2-1 and face SNEG of element 302 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 24 of instance POT2-1 and face SNEG of element 263 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 23 of instance POT2-1 and face SNEG of element 300 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 84 of instance POT2-1 and face SNEG of element 296 of instance PLAQUE-1
Initial node-face overclosure is 9.62565E-02 at node 262 of instance PLAQUE-1 and face SNEG of element 517 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 11 of instance POT2-1 and face SNEG of element 291 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 10 of instance POT2-1 and face SNEG of element 226 of instance PLAQUE-1
Initial node-face overclosure is 0.12060 at node 261 of instance PLAQUE-1 and face SNEG of element 516 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 102 of instance POT2-1 and face SNEG of element 294 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 101 of instance POT2-1 and face SNEG of element 305 of instance PLAQUE-1
Initial node-face overclosure is 7.47945E-02 at node 328 of instance PLAQUE-1 and face SNEG of element 130 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 577 of instance POT2-1 and face SNEG of element 305 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 576 of instance POT2-1 and face SNEG of element 287 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 575 of instance POT2-1 and face SNEG of element 305 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 570 of instance POT2-1 and face SNEG of element 287 of instance PLAQUE-1
Initial node-face overclosure is 0.12424 at node 315 of instance PLAQUE-1 and face SNEG of element 505 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 313 of instance PLAQUE-1 and face SNEG of element 497 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 94 of instance POT2-1 and face SNEG of element 326 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 93 of instance POT2-1 and face SNEG of element 317 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 573 of instance POT2-1 and face SNEG of element 316 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 571 of instance POT2-1 and face SNEG of element 303 of instance PLAQUE-1
Initial node-face overclosure is 8.82792E-02 at node 325 of instance PLAQUE-1 and face SNEG of element 510 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 317 of instance PLAQUE-1 and face SNEG of element 511 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 569 of instance POT2-1 and face SNEG of element 303 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 92 of instance POT2-1 and face SNEG of element 303 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 91 of instance POT2-1 and face SNEG of element 323 of instance PLAQUE-1
Initial node-face overclosure is 0.10823 at node 322 of instance PLAQUE-1 and face SNEG of element 496 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 97 of instance POT2-1 and face SNEG of element 318 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 96 of instance POT2-1 and face SNEG of element 327 of instance PLAQUE-1
Initial node-face overclosure is 8.48371E-02 at node 333 of instance PLAQUE-1 and face SNEG of element 491 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 22 of instance POT2-1 and face SNEG of element 320 of instance PLAQUE-1
Initial node-face overclosure is 0.12500 at node 578 of instance POT2-1 and face SNEG of element 322 of instance PLAQUE-1
Initial node-face overclosure is 7.49995E-02 at node 98 of instance POT2-1 and face SNEG of element 321 of instance PLAQUE-1
Initial node-face overclosure is 8.39039E-02 at node 321 of instance PLAQUE-1 and face SNEG of element 508 of instance POT2-1
Initial node-face overclosure is 0.12500 at node 572 of instance POT2-1 and face SNEG of element 316 of instance PLAQUE-1
Initial node-face overclosure is 7.50000E-02 at node 90 of instance POT2-1 and face SNEG of element 304 of instance PLAQUE-1
Initial node-face overclosure is 0.10554 at node 320 of instance PLAQUE-1 and face SNEG of element 513 of instance POT2-1
Initial node-face overclosure is 7.49981E-02 at node 141 of instance POT2-1 and face SNEG of element 207 of instance PLAQUE-2
Initial node-face overclosure is 0.14490 at node 267 of instance PLAQUE-2 and face SNEG of element 565 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 191 of instance POT2-1 and face SNEG of element 118 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 190 of instance POT2-1 and face SNEG of element 3 of instance PLAQUE-2
Initial node-face overclosure is 0.23896 at node 208 of instance PLAQUE-2 and face SNEG of element 565 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 189 of instance POT2-1 and face SNEG of element 193 of instance PLAQUE-2
Initial node-face overclosure is 7.49967E-02 at node 140 of instance POT2-1 and face SNEG of element 193 of instance PLAQUE-2
Initial node-face overclosure is 7.49971E-02 at node 136 of instance POT2-1 and face SNEG of element 222 of instance PLAQUE-2
Initial node-face overclosure is 7.49986E-02 at node 135 of instance POT2-1 and face SNEG of element 230 of instance PLAQUE-2
Initial node-face overclosure is 7.49980E-02 at node 137 of instance POT2-1 and face SNEG of element 224 of instance PLAQUE-2
Initial node-face overclosure is 7.80830E-02 at node 357 of instance PLAQUE-2 and face SNEG of element 542 of instance POT2-1
Initial node-face overclosure is 2.91009E-03 at node 357 of instance PLAQUE-2 and face SNEG of element 160 of instance POT2-1
Initial node-face overclosure is 7.49957E-02 at node 133 of instance POT2-1 and face SNEG of element 333 of instance PLAQUE-2
Initial node-face overclosure is 8.74463E-02 at node 274 of instance PLAQUE-2 and face SNEG of element 545 of instance POT2-1
Initial node-face overclosure is 7.49962E-02 at node 130 of instance POT2-1 and face SNEG of element 281 of instance PLAQUE-2
Initial node-face overclosure is 7.49981E-02 at node 129 of instance POT2-1 and face SNEG of element 334 of instance PLAQUE-2
Initial node-face overclosure is 7.49952E-02 at node 128 of instance POT2-1 and face SNEG of element 241 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 159 of instance POT2-1 and face SNEG of element 208 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 158 of instance POT2-1 and face SNEG of element 213 of instance PLAQUE-2
Initial node-face overclosure is 0.18676 at node 212 of instance PLAQUE-2 and face SNEG of element 557 of instance POT2-1
Initial node-face overclosure is 0.22456 at node 207 of instance PLAQUE-2 and face SNEG of element 566 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 186 of instance POT2-1 and face SNEG of element 220 of instance PLAQUE-2
Initial node-face overclosure is 0.21629 at node 216 of instance PLAQUE-2 and face SNEG of element 541 of instance POT2-1
Initial node-face overclosure is 0.23099 at node 214 of instance PLAQUE-2 and face SNEG of element 542 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 138 of instance POT2-1 and face SNEG of element 219 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 166 of instance POT2-1 and face SPOS of element 185 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 165 of instance POT2-1 and face SNEG of element 10 of instance PLAQUE-2
Initial node-face overclosure is 0.13903 at node 356 of instance PLAQUE-2 and face SNEG of element 553 of instance POT2-1
Initial node-face overclosure is 0.22842 at node 241 of instance PLAQUE-2 and face SNEG of element 552 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 164 of instance POT2-1 and face SNEG of element 228 of instance PLAQUE-2
Initial node-face overclosure is 0.23005 at node 240 of instance PLAQUE-2 and face SNEG of element 553 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 175 of instance POT2-1 and face SNEG of element 190 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 174 of instance POT2-1 and face SNEG of element 242 of instance PLAQUE-2
Initial node-face overclosure is 0.19181 at node 245 of instance PLAQUE-2 and face SNEG of element 547 of instance POT2-1
Initial node-face overclosure is 0.18233 at node 236 of instance PLAQUE-2 and face SNEG of element 547 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 173 of instance POT2-1 and face SNEG of element 255 of instance PLAQUE-2
Initial node-face overclosure is 0.20108 at node 252 of instance PLAQUE-2 and face SNEG of element 560 of instance POT2-1
Initial node-face overclosure is 0.20041 at node 251 of instance PLAQUE-2 and face SNEG of element 548 of instance POT2-1
Initial node-face overclosure is 7.49983E-02 at node 127 of instance POT2-1 and face SNEG of element 273 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 194 of instance POT2-1 and face SNEG of element 258 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 7 of instance POT2-1 and face SNEG of element 112 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 7 of instance POT2-1 and face SNEG of element 66 of instance PLAQUE-2
Initial node-face overclosure is 0.11875 at node 34 of instance PLAQUE-2 and face SNEG of element 559 of instance POT2-1
Initial node-face overclosure is 0.11875 at node 34 of instance PLAQUE-2 and face SNEG of element 537 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 182 of instance POT2-1 and face SNEG of element 149 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 177 of instance POT2-1 and face SNEG of element 194 of instance PLAQUE-2
Initial node-face overclosure is 7.49990E-02 at node 123 of instance POT2-1 and face SNEG of element 246 of instance PLAQUE-2
Initial node-face overclosure is 0.21864 at node 243 of instance PLAQUE-2 and face SNEG of element 551 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 167 of instance POT2-1 and face SNEG of element 34 of instance PLAQUE-2
Initial node-face overclosure is 0.21444 at node 242 of instance PLAQUE-2 and face SNEG of element 535 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 169 of instance POT2-1 and face SNEG of element 91 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 168 of instance POT2-1 and face SNEG of element 158 of instance PLAQUE-2
Initial node-face overclosure is 8.33651E-02 at node 360 of instance PLAQUE-2 and face SNEG of element 550 of instance POT2-1
Initial node-face overclosure is 0.20086 at node 246 of instance PLAQUE-2 and face SNEG of element 550 of instance POT2-1
Initial node-face overclosure is 0.22149 at node 244 of instance PLAQUE-2 and face SNEG of element 550 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 155 of instance POT2-1 and face SNEG of element 203 of instance PLAQUE-2
Initial node-face overclosure is 0.11043 at node 97 of instance PLAQUE-2 and face SNEG of element 559 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 156 of instance POT2-1 and face SNEG of element 114 of instance PLAQUE-2
Initial node-face overclosure is 7.49986E-02 at node 144 of instance POT2-1 and face SNEG of element 47 of instance PLAQUE-2
Initial node-face overclosure is 0.10841 at node 194 of instance PLAQUE-2 and face SNEG of element 569 of instance POT2-1
Initial node-face overclosure is 0.10518 at node 98 of instance PLAQUE-2 and face SNEG of element 537 of instance POT2-1
Initial node-face overclosure is 7.49981E-02 at node 5 of instance POT2-1 and face SNEG of element 110 of instance PLAQUE-2
Initial node-face overclosure is 7.50000E-02 at node 5 of instance POT2-1 and face SNEG of element 67 of instance PLAQUE-2
Initial node-face overclosure is 7.49981E-02 at node 113 of instance POT2-1 and face SNEG of element 44 of instance PLAQUE-2
Initial node-face overclosure is 0.12588 at node 198 of instance PLAQUE-2 and face SNEG of element 558 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 193 of instance POT2-1 and face SNEG of element 182 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 157 of instance POT2-1 and face SNEG of element 177 of instance PLAQUE-2
Initial node-face overclosure is 7.49990E-02 at node 115 of instance POT2-1 and face SNEG of element 268 of instance PLAQUE-2
Initial node-face overclosure is 7.49981E-02 at node 114 of instance POT2-1 and face SNEG of element 46 of instance PLAQUE-2
Initial node-face overclosure is 0.16161 at node 204 of instance PLAQUE-2 and face SNEG of element 566 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 163 of instance POT2-1 and face SNEG of element 225 of instance PLAQUE-2
Initial node-face overclosure is 0.22233 at node 239 of instance PLAQUE-2 and face SNEG of element 567 of instance POT2-1
Initial node-face overclosure is 0.23905 at node 234 of instance PLAQUE-2 and face SNEG of element 554 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 162 of instance POT2-1 and face SNEG of element 274 of instance PLAQUE-2
Initial node-face overclosure is 0.24888 at node 223 of instance PLAQUE-2 and face SNEG of element 534 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 187 of instance POT2-1 and face SNEG of element 73 of instance PLAQUE-2
Initial node-face overclosure is 0.17799 at node 215 of instance PLAQUE-2 and face SNEG of element 541 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 188 of instance POT2-1 and face SNEG of element 193 of instance PLAQUE-2
Initial node-face overclosure is 7.49971E-02 at node 139 of instance POT2-1 and face SNEG of element 270 of instance PLAQUE-2
Initial node-face overclosure is 0.13199 at node 213 of instance PLAQUE-2 and face SNEG of element 540 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 184 of instance POT2-1 and face SNEG of element 167 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 183 of instance POT2-1 and face SNEG of element 140 of instance PLAQUE-2
Initial node-face overclosure is 0.19296 at node 222 of instance PLAQUE-2 and face SNEG of element 530 of instance POT2-1
Initial node-face overclosure is 0.18751 at node 220 of instance PLAQUE-2 and face SNEG of element 543 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 185 of instance POT2-1 and face SNEG of element 168 of instance PLAQUE-2
Initial node-face overclosure is 0.19461 at node 219 of instance PLAQUE-2 and face SNEG of element 564 of instance POT2-1
Initial node-face overclosure is 0.21835 at node 217 of instance PLAQUE-2 and face SNEG of element 564 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 181 of instance POT2-1 and face SNEG of element 166 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 180 of instance POT2-1 and face SNEG of element 277 of instance PLAQUE-2
Initial node-face overclosure is 0.15518 at node 225 of instance PLAQUE-2 and face SNEG of element 544 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 179 of instance POT2-1 and face SNEG of element 137 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 178 of instance POT2-1 and face SNEG of element 125 of instance PLAQUE-2
Initial node-face overclosure is 7.50000E-02 at node 132 of instance POT2-1 and face SNEG of element 235 of instance PLAQUE-2
Initial node-face overclosure is 0.16789 at node 231 of instance PLAQUE-2 and face SNEG of element 562 of instance POT2-1
Initial node-face overclosure is 0.22895 at node 230 of instance PLAQUE-2 and face SNEG of element 562 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 176 of instance POT2-1 and face SNEG of element 152 of instance PLAQUE-2
Initial node-face overclosure is 0.19100 at node 235 of instance PLAQUE-2 and face SNEG of element 561 of instance POT2-1
Initial node-face overclosure is 0.17622 at node 233 of instance PLAQUE-2 and face SNEG of element 546 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 172 of instance POT2-1 and face SNEG of element 250 of instance PLAQUE-2
Initial node-face overclosure is 0.22854 at node 250 of instance PLAQUE-2 and face SNEG of element 560 of instance POT2-1
Initial node-face overclosure is 0.25000 at node 171 of instance POT2-1 and face SNEG of element 248 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 170 of instance POT2-1 and face SNEG of element 247 of instance PLAQUE-2
Initial node-face overclosure is 7.49976E-02 at node 125 of instance POT2-1 and face SNEG of element 249 of instance PLAQUE-2
Initial node-face overclosure is 0.15366 at node 248 of instance PLAQUE-2 and face SNEG of element 549 of instance POT2-1
Initial node-face overclosure is 0.19123 at node 247 of instance PLAQUE-2 and face SNEG of element 568 of instance POT2-1
Initial node-face overclosure is 7.49990E-02 at node 124 of instance POT2-1 and face SNEG of element 337 of instance PLAQUE-2
Initial node-face overclosure is 7.50000E-02 at node 122 of instance POT2-1 and face SNEG of element 284 of instance PLAQUE-2
Initial node-face overclosure is 7.49990E-02 at node 121 of instance POT2-1 and face SNEG of element 312 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 192 of instance POT2-1 and face SNEG of element 202 of instance PLAQUE-2
Initial node-face overclosure is 7.49990E-02 at node 143 of instance POT2-1 and face SNEG of element 146 of instance PLAQUE-2
Initial node-face overclosure is 7.49990E-02 at node 142 of instance POT2-1 and face SNEG of element 141 of instance PLAQUE-2
Initial node-face overclosure is 0.17377 at node 206 of instance PLAQUE-2 and face SNEG of element 538 of instance POT2-1
Initial node-face overclosure is 0.12807 at node 205 of instance PLAQUE-2 and face SNEG of element 538 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 116 of instance POT2-1 and face SNEG of element 153 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 160 of instance POT2-1 and face SNEG of element 184 of instance PLAQUE-2
Initial node-face overclosure is 7.49962E-02 at node 117 of instance POT2-1 and face SNEG of element 269 of instance PLAQUE-2
Initial node-face overclosure is 0.23159 at node 221 of instance PLAQUE-2 and face SNEG of element 555 of instance POT2-1
Initial node-face overclosure is 0.19791 at node 218 of instance PLAQUE-2 and face SNEG of element 556 of instance POT2-1
Initial node-face overclosure is 7.49986E-02 at node 131 of instance POT2-1 and face SNEG of element 239 of instance PLAQUE-2
Initial node-face overclosure is 0.11084 at node 232 of instance PLAQUE-2 and face SNEG of element 546 of instance POT2-1
Initial node-face overclosure is 7.49966E-02 at node 126 of instance POT2-1 and face SNEG of element 314 of instance PLAQUE-2
Initial node-face overclosure is 0.11766 at node 249 of instance PLAQUE-2 and face SNEG of element 532 of instance POT2-1
Initial node-face overclosure is 7.49981E-02 at node 120 of instance POT2-1 and face SNEG of element 240 of instance PLAQUE-2
Initial node-face overclosure is 7.49981E-02 at node 119 of instance POT2-1 and face SNEG of element 234 of instance PLAQUE-2
Initial node-face overclosure is 0.25000 at node 161 of instance POT2-1 and face SNEG of element 200 of instance PLAQUE-2
Initial node-face overclosure is 7.49981E-02 at node 118 of instance POT2-1 and face SNEG of element 299 of instance PLAQUE-2
Initial node-face overclosure is 0.13320 at node 354 of instance PLAQUE-2 and face SNEG of element 554 of instance POT2-1
Initial node-face overclosure is 9.75188E-02 at node 351 of instance PLAQUE-2 and face SNEG of element 555 of instance POT2-1
Initial node-face overclosure is 8.76681E-02 at node 271 of instance PLAQUE-2 and face SNEG of element 554 of instance POT2-1
Initial node-face overclosure is 7.50000E-02 at node 134 of instance POT2-1 and face SNEG of element 231 of instance PLAQUE-2
Initial node-face overclosure is 0.17347 at node 224 of instance PLAQUE-2 and face SNEG of element 563 of instance POT2-1



  Adjacent slave nodes 141 and 294 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 207 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 141 and 295 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 207 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 269 and 348 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 157 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 267 and 269 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 157 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 267 and 349 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 156 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 267 and 294 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 156 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 208 and 349 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 156 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 140 and 295 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 193 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 140 and 296 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 193 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 211 and 269 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 157 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 136 and 299 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 222 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 136 and 300 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 222 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 135 and 300 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 230 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 135 and 301 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 230 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 137 and 298 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 224 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 137 and 299 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 224 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 353 and 357 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 160 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 312 and 357 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 160 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 133 and 302 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 333 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 133 and 303 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 333 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 274 and 280 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 165 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 274 and 332 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 165 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 274 and 340 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 165 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 130 and 305 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 281 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 130 and 306 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 281 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 129 and 306 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 334 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 129 and 307 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 334 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 128 and 307 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 241 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 128 and 308 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 241 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 212 and 293 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 182 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 212 and 266 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 181 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 209 and 293 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 182 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 207 and 293 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 182 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 207 and 264 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 183 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 216 and 270 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 160 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 216 and 311 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 159 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 214 and 270 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 160 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 138 and 297 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 219 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 138 and 298 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 219 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 270 and 357 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 160 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 166 and 167 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 93 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 165 and 166 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 244 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 241 and 242 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 535 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 241 and 361 of instance PLAQUE-2 may be on the same
  side of a surface near face SPOS of element 535 of instance POT2-1 but still
  crossed the surface in the configuration after the initial overclosure
  procedure.


  Adjacent slave nodes 241 and 343 of instance PLAQUE-2 may be on the same
  side of a surface near face SPOS of element 552 of instance POT2-1 but still
  crossed the surface in the configuration after the initial overclosure
  procedure.


  Adjacent slave nodes 241 and 343 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 176 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 241 and 361 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 175 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 238 and 343 of instance PLAQUE-2 may be on the same
  side of a surface near face SPOS of element 552 of instance POT2-1 but still
  crossed the surface in the configuration after the initial overclosure
  procedure.


  Adjacent slave nodes 238 and 343 of instance PLAQUE-2 may be on the same
  side of a surface near face SPOS of element 552 of instance POT2-1 but still
  crossed the surface in the configuration after the initial overclosure
  procedure.


  Adjacent slave nodes 238 and 343 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 176 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 240 and 355 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 178 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 240 and 278 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 177 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 245 and 339 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 170 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 245 and 342 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 169 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 236 and 342 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 169 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 236 and 352 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 168 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 252 and 341 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 171 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 251 and 339 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 170 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 251 and 341 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 170 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 127 and 308 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 273 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 127 and 309 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 273 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 34 and 35 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 185 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 34 and 35 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 153 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 123 and 312 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 246 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 123 and 313 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 246 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 279 and 360 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 174 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 243 and 279 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 175 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 242 and 279 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 175 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 242 and 361 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 175 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 246 and 276 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 174 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 246 and 359 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 173 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 97 and 99 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 185 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 144 and 291 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 47 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 144 and 292 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 47 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 196 and 205 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 155 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 194 and 196 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 154 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 100 and 194 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 154 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 98 and 100 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 153 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 5 and 145 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 110 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 5 and 291 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 67 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 5 and 145 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 67 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 35 and 97 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 185 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 35 and 98 of instance PLAQUE-2 may be on opposite sides
  of a surface near face SPOS of element 153 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 113 and 322 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 44 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 113 and 145 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 44 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 192 and 198 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 184 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 192 and 204 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 183 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 99 and 198 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 184 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 115 and 320 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 268 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 115 and 321 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 268 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 114 and 321 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 46 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 114 and 322 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 46 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 204 and 264 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 183 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 239 and 355 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 178 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 239 and 273 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 179 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 234 and 273 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 179 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 215 and 311 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 159 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 215 and 268 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 159 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 139 and 296 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 270 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 139 and 297 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 270 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 213 and 269 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 158 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 213 and 268 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 158 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 222 and 272 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 162 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 220 and 358 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 162 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 220 and 272 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 162 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 219 and 358 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 161 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 219 and 353 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 161 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 225 and 340 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 164 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 225 and 275 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 163 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 132 and 303 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 235 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 132 and 304 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 235 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 231 and 280 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 166 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 231 and 336 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 166 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 230 and 280 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 166 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 235 and 277 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 168 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 235 and 352 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 168 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 233 and 277 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 168 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 250 and 341 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 171 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 125 and 310 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 249 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 125 and 311 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 249 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 248 and 359 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 173 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 248 and 281 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 172 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 247 and 359 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 173 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 124 and 311 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 337 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 124 and 312 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 337 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 276 and 360 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 174 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 122 and 313 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 284 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 122 and 314 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 284 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 122 and 166 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 284 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 121 and 314 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 312 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 121 and 315 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 312 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 121 and 166 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 244 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 343 and 356 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 176 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 143 and 292 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 146 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 143 and 293 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 146 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 142 and 293 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 141 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 142 and 294 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 141 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 206 and 349 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 156 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 206 and 265 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 155 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 205 and 265 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 155 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 116 and 319 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 153 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 116 and 320 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 153 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 117 and 318 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 269 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 117 and 319 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 269 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 218 and 266 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 181 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 218 and 295 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 181 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 131 and 304 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 239 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 131 and 305 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 239 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 232 and 336 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 167 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 232 and 277 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 167 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 232 and 282 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 167 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 126 and 309 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 314 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 126 and 310 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 314 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 249 and 283 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 172 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 249 and 281 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 172 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 249 and 341 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 171 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 295 and 351 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 180 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 120 and 315 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 240 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 120 and 316 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 240 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 327 and 356 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 177 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 278 and 356 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 177 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 119 and 316 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 234 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 119 and 317 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 234 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 304 and 354 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 179 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 304 and 351 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 180 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 273 and 354 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 179 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 118 and 317 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 299 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 118 and 318 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 299 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 271 and 304 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 179 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 134 and 301 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 231 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 134 and 302 of instance POT2-1 may be on opposite sides
  of a surface near face SPOS of element 231 of instance PLAQUE-2 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 224 and 275 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 163 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 224 and 272 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 162 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Adjacent slave nodes 338 and 360 of instance PLAQUE-2 may be on opposite
  sides of a surface near face SPOS of element 174 of instance POT2-1 in the
  configuration after the initial overclosure procedure.


  Actual adjustments of nodal positions for slave nodes in general contact

Initial contact adjustment is 0.12500 at node 1 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 4 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 5 of instance POT2-1
Initial contact adjustment is 0.26167 at node 7 of instance POT2-1
Initial contact adjustment is 0.12500 at node 8 of instance POT2-1
Initial contact adjustment is 0.12500 at node 9 of instance POT2-1
Initial contact adjustment is 0.12500 at node 10 of instance POT2-1
Initial contact adjustment is 0.12500 at node 11 of instance POT2-1
Initial contact adjustment is 0.12500 at node 12 of instance POT2-1
Initial contact adjustment is 0.12500 at node 13 of instance POT2-1
Initial contact adjustment is 0.12500 at node 14 of instance POT2-1
Initial contact adjustment is 0.12500 at node 15 of instance POT2-1
Initial contact adjustment is 0.12500 at node 16 of instance POT2-1
Initial contact adjustment is 0.12500 at node 17 of instance POT2-1
Initial contact adjustment is 0.12500 at node 18 of instance POT2-1
Initial contact adjustment is 0.12500 at node 19 of instance POT2-1
Initial contact adjustment is 0.12500 at node 20 of instance POT2-1
Initial contact adjustment is 0.12500 at node 21 of instance POT2-1
Initial contact adjustment is 0.12500 at node 22 of instance POT2-1
Initial contact adjustment is 0.12500 at node 23 of instance POT2-1
Initial contact adjustment is 0.12500 at node 24 of instance POT2-1
Initial contact adjustment is 0.12500 at node 25 of instance POT2-1
Initial contact adjustment is 0.12500 at node 26 of instance POT2-1
Initial contact adjustment is 7.49987E-02 at node 81 of instance POT2-1
Initial contact adjustment is 7.49972E-02 at node 82 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 83 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 84 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 85 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 86 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 87 of instance POT2-1
Initial contact adjustment is 7.49987E-02 at node 88 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 89 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 90 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 91 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 92 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 93 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 94 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 95 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 96 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 97 of instance POT2-1
Initial contact adjustment is 7.50008E-02 at node 98 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 99 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 100 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 101 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 102 of instance POT2-1
Initial contact adjustment is 7.49987E-02 at node 103 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 104 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 105 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 106 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 107 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 108 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 109 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 110 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 111 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 112 of instance POT2-1
Initial contact adjustment is 7.50006E-02 at node 113 of instance POT2-1
Initial contact adjustment is 7.50006E-02 at node 114 of instance POT2-1
Initial contact adjustment is 7.50011E-02 at node 115 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 116 of instance POT2-1
Initial contact adjustment is 7.49996E-02 at node 117 of instance POT2-1
Initial contact adjustment is 7.50006E-02 at node 118 of instance POT2-1
Initial contact adjustment is 7.50006E-02 at node 119 of instance POT2-1
Initial contact adjustment is 7.50006E-02 at node 120 of instance POT2-1
Initial contact adjustment is 7.50011E-02 at node 121 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 122 of instance POT2-1
Initial contact adjustment is 7.50011E-02 at node 123 of instance POT2-1
Initial contact adjustment is 7.50011E-02 at node 124 of instance POT2-1
Initial contact adjustment is 7.50003E-02 at node 125 of instance POT2-1
Initial contact adjustment is 7.49998E-02 at node 126 of instance POT2-1
Initial contact adjustment is 7.50007E-02 at node 127 of instance POT2-1
Initial contact adjustment is 7.49982E-02 at node 128 of instance POT2-1
Initial contact adjustment is 7.50006E-02 at node 129 of instance POT2-1
Initial contact adjustment is 7.49996E-02 at node 130 of instance POT2-1
Initial contact adjustment is 7.50008E-02 at node 131 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 132 of instance POT2-1
Initial contact adjustment is 7.49989E-02 at node 133 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 134 of instance POT2-1
Initial contact adjustment is 7.50008E-02 at node 135 of instance POT2-1
Initial contact adjustment is 7.50001E-02 at node 136 of instance POT2-1
Initial contact adjustment is 7.50005E-02 at node 137 of instance POT2-1
Initial contact adjustment is 7.50015E-02 at node 138 of instance POT2-1
Initial contact adjustment is 7.50001E-02 at node 139 of instance POT2-1
Initial contact adjustment is 7.49999E-02 at node 140 of instance POT2-1
Initial contact adjustment is 7.50006E-02 at node 141 of instance POT2-1
Initial contact adjustment is 7.50010E-02 at node 142 of instance POT2-1
Initial contact adjustment is 7.50010E-02 at node 143 of instance POT2-1
Initial contact adjustment is 7.50008E-02 at node 144 of instance POT2-1
Initial contact adjustment is 0.26136 at node 155 of instance POT2-1
Initial contact adjustment is 0.26096 at node 156 of instance POT2-1
Initial contact adjustment is 0.26091 at node 157 of instance POT2-1
Initial contact adjustment is 0.26132 at node 158 of instance POT2-1
Initial contact adjustment is 0.26163 at node 159 of instance POT2-1
Initial contact adjustment is 0.26140 at node 160 of instance POT2-1
Initial contact adjustment is 0.26101 at node 161 of instance POT2-1
Initial contact adjustment is 0.26086 at node 162 of instance POT2-1
Initial contact adjustment is 0.26126 at node 163 of instance POT2-1
Initial contact adjustment is 0.26160 at node 164 of instance POT2-1
Initial contact adjustment is 0.26144 at node 165 of instance POT2-1
Initial contact adjustment is 0.28235 at node 166 of instance POT2-1
Initial contact adjustment is 0.26080 at node 167 of instance POT2-1
Initial contact adjustment is 0.26122 at node 168 of instance POT2-1
Initial contact adjustment is 0.26156 at node 169 of instance POT2-1
Initial contact adjustment is 0.26149 at node 170 of instance POT2-1
Initial contact adjustment is 0.26112 at node 171 of instance POT2-1
Initial contact adjustment is 0.26074 at node 172 of instance POT2-1
Initial contact adjustment is 0.26117 at node 173 of instance POT2-1
Initial contact adjustment is 0.26153 at node 174 of instance POT2-1
Initial contact adjustment is 0.26153 at node 175 of instance POT2-1
Initial contact adjustment is 0.26117 at node 176 of instance POT2-1
Initial contact adjustment is 0.26074 at node 177 of instance POT2-1
Initial contact adjustment is 0.26112 at node 178 of instance POT2-1
Initial contact adjustment is 0.26148 at node 179 of instance POT2-1
Initial contact adjustment is 0.26155 at node 180 of instance POT2-1
Initial contact adjustment is 0.26122 at node 181 of instance POT2-1
Initial contact adjustment is 0.26080 at node 182 of instance POT2-1
Initial contact adjustment is 0.26107 at node 183 of instance POT2-1
Initial contact adjustment is 0.26144 at node 184 of instance POT2-1
Initial contact adjustment is 0.26159 at node 185 of instance POT2-1
Initial contact adjustment is 0.26127 at node 186 of instance POT2-1
Initial contact adjustment is 0.26085 at node 187 of instance POT2-1
Initial contact adjustment is 0.26102 at node 188 of instance POT2-1
Initial contact adjustment is 0.26140 at node 189 of instance POT2-1
Initial contact adjustment is 0.26163 at node 190 of instance POT2-1
Initial contact adjustment is 0.26131 at node 191 of instance POT2-1
Initial contact adjustment is 0.26091 at node 192 of instance POT2-1
Initial contact adjustment is 0.26096 at node 193 of instance POT2-1
Initial contact adjustment is 0.26136 at node 194 of instance POT2-1
Initial contact adjustment is 0.12500 at node 569 of instance POT2-1
Initial contact adjustment is 0.12500 at node 570 of instance POT2-1
Initial contact adjustment is 0.12500 at node 571 of instance POT2-1
Initial contact adjustment is 0.12500 at node 572 of instance POT2-1
Initial contact adjustment is 0.12500 at node 573 of instance POT2-1
Initial contact adjustment is 0.12500 at node 574 of instance POT2-1
Initial contact adjustment is 0.12500 at node 575 of instance POT2-1
Initial contact adjustment is 0.12500 at node 576 of instance POT2-1
Initial contact adjustment is 0.12500 at node 577 of instance POT2-1
Initial contact adjustment is 0.12500 at node 578 of instance POT2-1

   3 unresolved initial node-face overclosure(s) will be stored as offsets


Unresolved initial overclosure is 2.90813E-03 between node 357 of instance PLAQUE-2 and face SNEG of element 160 of instance POT2-1
Unresolved initial overclosure is 0.46278 between node 241 of instance PLAQUE-2 and face SNEG of element 552 of instance POT2-1
Unresolved initial overclosure is 6.69183E-02 between node 242 of instance PLAQUE-2 and face SNEG of element 535 of instance POT2-1

------------------------------------------------------------------------------
